# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import NoiseWaveformsAndPSDensity_pb2 as NoiseWaveformsAndPSDensity__pb2


class SignalGeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplySignalParameters = channel.unary_unary(
                '/example.SignalGeneratorService/ApplySignalParameters',
                request_serializer=NoiseWaveformsAndPSDensity__pb2.SignalParameters.SerializeToString,
                response_deserializer=NoiseWaveformsAndPSDensity__pb2.noData.FromString,
                )
        self.ApplyNoiseParameters = channel.unary_unary(
                '/example.SignalGeneratorService/ApplyNoiseParameters',
                request_serializer=NoiseWaveformsAndPSDensity__pb2.NoiseParameters.SerializeToString,
                response_deserializer=NoiseWaveformsAndPSDensity__pb2.noData.FromString,
                )
        self.GenerateSignal = channel.unary_unary(
                '/example.SignalGeneratorService/GenerateSignal',
                request_serializer=NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
                response_deserializer=NoiseWaveformsAndPSDensity__pb2.SignalData.FromString,
                )
        self.GetAnalyzedParameters = channel.unary_unary(
                '/example.SignalGeneratorService/GetAnalyzedParameters',
                request_serializer=NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
                response_deserializer=NoiseWaveformsAndPSDensity__pb2.AnalyzedResults.FromString,
                )


class SignalGeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplySignalParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyNoiseParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalyzedParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SignalGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplySignalParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplySignalParameters,
                    request_deserializer=NoiseWaveformsAndPSDensity__pb2.SignalParameters.FromString,
                    response_serializer=NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
            ),
            'ApplyNoiseParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyNoiseParameters,
                    request_deserializer=NoiseWaveformsAndPSDensity__pb2.NoiseParameters.FromString,
                    response_serializer=NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
            ),
            'GenerateSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSignal,
                    request_deserializer=NoiseWaveformsAndPSDensity__pb2.noData.FromString,
                    response_serializer=NoiseWaveformsAndPSDensity__pb2.SignalData.SerializeToString,
            ),
            'GetAnalyzedParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalyzedParameters,
                    request_deserializer=NoiseWaveformsAndPSDensity__pb2.noData.FromString,
                    response_serializer=NoiseWaveformsAndPSDensity__pb2.AnalyzedResults.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.SignalGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SignalGeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplySignalParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.SignalGeneratorService/ApplySignalParameters',
            NoiseWaveformsAndPSDensity__pb2.SignalParameters.SerializeToString,
            NoiseWaveformsAndPSDensity__pb2.noData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyNoiseParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.SignalGeneratorService/ApplyNoiseParameters',
            NoiseWaveformsAndPSDensity__pb2.NoiseParameters.SerializeToString,
            NoiseWaveformsAndPSDensity__pb2.noData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.SignalGeneratorService/GenerateSignal',
            NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
            NoiseWaveformsAndPSDensity__pb2.SignalData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAnalyzedParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.SignalGeneratorService/GetAnalyzedParameters',
            NoiseWaveformsAndPSDensity__pb2.noData.SerializeToString,
            NoiseWaveformsAndPSDensity__pb2.AnalyzedResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
