# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NoiseWaveformsAndPSDensity.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NoiseWaveformsAndPSDensity.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n NoiseWaveformsAndPSDensity.proto\x12\x07\x65xample\">\n\x0cSamplingInfo\x12\x19\n\x11number_of_samples\x18\x01 \x01(\x05\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x02\"f\n\x10SignalParameters\x12,\n\rsampling_info\x18\x01 \x01(\x0b\x32\x15.example.SamplingInfo\x12\x11\n\tfrequency\x18\x02 \x01(\x02\x12\x11\n\tamplitude\x18\x03 \x01(\x02\"\x1a\n\x06noData\x12\x10\n\x08response\x18\x01 \x01(\t\"j\n\x0fNoiseParameters\x12,\n\rsampling_info\x18\x01 \x01(\x0b\x32\x15.example.SamplingInfo\x12\x16\n\x0enoiseamplitude\x18\x02 \x01(\x02\x12\x11\n\tnoisetype\x18\x03 \x01(\x05\"\x1d\n\nSignalData\x12\x0f\n\x07samples\x18\x01 \x03(\x02\"8\n\x0f\x41nalyzedResults\x12\r\n\x05sinad\x18\x01 \x01(\x02\x12\x16\n\x0eTHD_plus_noise\x18\x02 \x01(\x02\x32\x9c\x02\n\x16SignalGeneratorService\x12\x43\n\x15\x41pplySignalParameters\x12\x19.example.SignalParameters\x1a\x0f.example.noData\x12\x41\n\x14\x41pplyNoiseParameters\x12\x18.example.NoiseParameters\x1a\x0f.example.noData\x12\x36\n\x0eGenerateSignal\x12\x0f.example.noData\x1a\x13.example.SignalData\x12\x42\n\x15GetAnalyzedParameters\x12\x0f.example.noData\x1a\x18.example.AnalyzedResultsb\x06proto3'
)




_SAMPLINGINFO = _descriptor.Descriptor(
  name='SamplingInfo',
  full_name='example.SamplingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_samples', full_name='example.SamplingInfo.number_of_samples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='example.SamplingInfo.sample_rate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=107,
)


_SIGNALPARAMETERS = _descriptor.Descriptor(
  name='SignalParameters',
  full_name='example.SignalParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampling_info', full_name='example.SignalParameters.sampling_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='example.SignalParameters.frequency', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amplitude', full_name='example.SignalParameters.amplitude', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=211,
)


_NODATA = _descriptor.Descriptor(
  name='noData',
  full_name='example.noData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='example.noData.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=239,
)


_NOISEPARAMETERS = _descriptor.Descriptor(
  name='NoiseParameters',
  full_name='example.NoiseParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sampling_info', full_name='example.NoiseParameters.sampling_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noiseamplitude', full_name='example.NoiseParameters.noiseamplitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='noisetype', full_name='example.NoiseParameters.noisetype', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=347,
)


_SIGNALDATA = _descriptor.Descriptor(
  name='SignalData',
  full_name='example.SignalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples', full_name='example.SignalData.samples', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=378,
)


_ANALYZEDRESULTS = _descriptor.Descriptor(
  name='AnalyzedResults',
  full_name='example.AnalyzedResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sinad', full_name='example.AnalyzedResults.sinad', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='THD_plus_noise', full_name='example.AnalyzedResults.THD_plus_noise', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=436,
)

_SIGNALPARAMETERS.fields_by_name['sampling_info'].message_type = _SAMPLINGINFO
_NOISEPARAMETERS.fields_by_name['sampling_info'].message_type = _SAMPLINGINFO
DESCRIPTOR.message_types_by_name['SamplingInfo'] = _SAMPLINGINFO
DESCRIPTOR.message_types_by_name['SignalParameters'] = _SIGNALPARAMETERS
DESCRIPTOR.message_types_by_name['noData'] = _NODATA
DESCRIPTOR.message_types_by_name['NoiseParameters'] = _NOISEPARAMETERS
DESCRIPTOR.message_types_by_name['SignalData'] = _SIGNALDATA
DESCRIPTOR.message_types_by_name['AnalyzedResults'] = _ANALYZEDRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SamplingInfo = _reflection.GeneratedProtocolMessageType('SamplingInfo', (_message.Message,), {
  'DESCRIPTOR' : _SAMPLINGINFO,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.SamplingInfo)
  })
_sym_db.RegisterMessage(SamplingInfo)

SignalParameters = _reflection.GeneratedProtocolMessageType('SignalParameters', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALPARAMETERS,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.SignalParameters)
  })
_sym_db.RegisterMessage(SignalParameters)

noData = _reflection.GeneratedProtocolMessageType('noData', (_message.Message,), {
  'DESCRIPTOR' : _NODATA,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.noData)
  })
_sym_db.RegisterMessage(noData)

NoiseParameters = _reflection.GeneratedProtocolMessageType('NoiseParameters', (_message.Message,), {
  'DESCRIPTOR' : _NOISEPARAMETERS,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.NoiseParameters)
  })
_sym_db.RegisterMessage(NoiseParameters)

SignalData = _reflection.GeneratedProtocolMessageType('SignalData', (_message.Message,), {
  'DESCRIPTOR' : _SIGNALDATA,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.SignalData)
  })
_sym_db.RegisterMessage(SignalData)

AnalyzedResults = _reflection.GeneratedProtocolMessageType('AnalyzedResults', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEDRESULTS,
  '__module__' : 'NoiseWaveformsAndPSDensity_pb2'
  # @@protoc_insertion_point(class_scope:example.AnalyzedResults)
  })
_sym_db.RegisterMessage(AnalyzedResults)



_SIGNALGENERATORSERVICE = _descriptor.ServiceDescriptor(
  name='SignalGeneratorService',
  full_name='example.SignalGeneratorService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=439,
  serialized_end=723,
  methods=[
  _descriptor.MethodDescriptor(
    name='ApplySignalParameters',
    full_name='example.SignalGeneratorService.ApplySignalParameters',
    index=0,
    containing_service=None,
    input_type=_SIGNALPARAMETERS,
    output_type=_NODATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ApplyNoiseParameters',
    full_name='example.SignalGeneratorService.ApplyNoiseParameters',
    index=1,
    containing_service=None,
    input_type=_NOISEPARAMETERS,
    output_type=_NODATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GenerateSignal',
    full_name='example.SignalGeneratorService.GenerateSignal',
    index=2,
    containing_service=None,
    input_type=_NODATA,
    output_type=_SIGNALDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAnalyzedParameters',
    full_name='example.SignalGeneratorService.GetAnalyzedParameters',
    index=3,
    containing_service=None,
    input_type=_NODATA,
    output_type=_ANALYZEDRESULTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIGNALGENERATORSERVICE)

DESCRIPTOR.services_by_name['SignalGeneratorService'] = _SIGNALGENERATORSERVICE

# @@protoc_insertion_point(module_scope)
